baseURL = "https://lhj8390.github.io/"
languageCode = "ko"
DefaultContentLanguage = "ko"
title = "Website of lhj8390"


# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "hugo-blog"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "monokai"

[outputs]
    home = [ "HTML", "RSS", "JSON"]
[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true
    [markup.highlight]
        codeFences = true
        guessSyntax = false
        hl_Lines = ''
        lineAnchors = ''
        lineNoStart = 1
        lineNos = true
        lineNumbersInTable = false
        noClasses = true
        noHl = false
        style = 'monokai'
        tabWidth = 4

[taxonomies]
    category = "categories"
    subcategory = "subcategories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80